# Crypto Classifier Pipeline Configuration

data:
  symbol: BTCUSDT
  interval: 1m
  start_date: '2020-01'
  end_date: '2020-01'

image:
  seq_len: 100  # Number of candles per image
  candle_width_ratio: 0.8  # 0.0-1.0, how wide candles are
  resolution:
    width: 800
    height: 500
  colors:
    bullish: 0.2  # Dark gray for bullish candles
    bearish: 0.0  # Black for bearish candles
  rendering:
    mode: gpu
    gpu_batch_size: 2000  # Can handle more with shared memory

paths:
  raw_data: data/raw
  processed_data: data/processed
  models: models
  logs: logs

pipeline:
  skip_existing_images: true
  num_workers: -1  # -1 means cpu_count() - 1


